if game.PlaceId == 13643807539 or game.PlaceId == 14413475235 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/yxllxws/nebula/refs/heads/main/lua/sbtt.luau'))()
elseif game.PlaceId == 71955570728487 or game.PlaceId == 126810591649091 or game.PlaceId == 87988573734660 then -- // south bronx remake support!!!
    loadstring(game:HttpGet('https://raw.githubusercontent.com/yxllxws/nebula/refs/heads/main/lua/sbttremakes.luau'))()
elseif game.PlaceId == 11177482306 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/yxllxws/nebula/refs/heads/main/lua/streetzwar2.luau'))()
elseif game.PlaceId == 16472538603 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/yxllxws/nebula/refs/heads/main/lua/thabronx3.luau'))()
elseif game.PlaceId == 110238095828503 then
    while true do while true do end end
end
