if game.PlaceId == 13643807539 or game.PlaceId == 14413475235 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/yxllxws/nebula/refs/heads/main/lua/sbtt.luau'))()
elseif game.PlaceIdd == 11177482306 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/yxllxws/nebula/refs/heads/main/lua/streetzwar2.luau'))()
elseif game.PlaceIdd == 16472538603 then
    loadstring(game:HttpGet('https://raw.githubusercontent.com/yxllxws/nebula/refs/heads/main/lua/thabronx3.luau'))()
end
